### ISSUE TITLE
Warning: Undefined array key "id" on searchCharacter

### ISSUE THREAD

**Issue by SirEdeonX** [Simbiat/lodestone-parser#3]
Results are populated but without the characters found. It seems to be a problem with the Parser.

#result: [
    "characters" => [
      "pageCurrent" => "1"
      "pageTotal" => "1"
      "total" => "4"
   ]
]
  
#errors: [
    0 => [
      "type" => "searchCharacter"
      "id" => null
      "error" => "Warning: Undefined array key "id""
      "url" => "https://na.finalfantasyxiv.com/lodestone/character/?q=vails&worldname=Shiva&page=1"
    ]
  ]

**Comment by Simbiat** [comment]
Probably something changed in how data is shown on Lodestone. I am not actively using `searchCharacter`, so was not aware. I will look into this today.

**Comment by Simbiat** [comment]
Fixed.
